config/routes.rb
Rails.application.routes.draw do
  mount API::Base, at: "/"
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  scope "(:locale)", locale: /en|vi/ do
    require "sidekiq/web"
    mount Sidekiq::Web => "/sidekiq"
    root "products#index"
    devise_for :users, skip: :omniauth_callbacks
    resources :products
    resources :carts
    resources :orders
    resources :orders_history, only: %i(index show)
    namespace :admins do
      root "products#index"
      resources :products
      resources :users
      resources :orders
    end
  end
end

app/controllers/orders_history_controller.rb
class OrdersHistoryController < ApplicationController
  before_action :authenticate_user!
  before_action :find_order, only: %i(show)

  load_and_authorize_resource Order, User

  def index
    @orders = current_user.orders
                          .includes(:order_details)
                          .page(params[:page]).per Settings.per_page
  end

  def show
    @product_items = @order.order_details.includes :product
  end

  private

  def find_order
    @order = Order.find_by id: params[:id]
    return if @order

    flash[:danger] = t ".unknown_order"
    redirect_to root_path
  end
end

app/views/orders_history/_order_item.html.erb
<tr>
  <td><%= order.id %></td>
  <td><%= order.created_at.strftime Settings.format_date %></td>
  <td><%= order.total_quantity %></td>
  <td class="product-price"><%= number_to_currency order.total_amount %></td>
  <td><%= t "admins.orders.form_search.#{order.status}" %></td>
  <td class="project-actions text-left">
    <%= link_to t(".show"), orders_history_path(order), class: "btn btn-primary btn-sm" %>
  </td>
</tr>

app/views/orders_history/_product_item.html.erb
<tr>
  <td class="shoping__cart__item">
    <%= image_tag order_detail.product.images.first.image_data, class: "order-detail-img" %>
    <h5><%= link_to order_detail.product.name, product_path(order_detail.product) %></h5>
  </td>
  <td class="shoping__cart__price">
    <%= order_detail.quantity %>
  </td>
  <td class="shoping__cart__price">
    <%= number_to_currency order_detail.amount %>
  </td>
</tr>

app/views/orders_history/index.html.erb
<main>
  <div class="order-detail">
    <div class="order-detail-container-big">
      <h1 class="mt-4"><%= t".list_orders" %></h1>
      <br>
      <div class="card mb-4">
        <div class="card-body">
          <div class="table-responsive">
            <h6 class="text-right">
              <span><%= t ".counts" %><%= @orders.total_count %></span>
            </h6>
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th><%= t ".id" %></th>
                  <th><%= t ".date" %></th>
                  <th><%= t ".quantity" %></th>
                  <th><%= t ".amount" %></th>
                  <th><%= t ".status" %></th>
                  <th><%= t ".action" %></th>
                </tr>
              </thead>
              <tbody>
                <%= render partial: "order_item", collection: @orders, as: :order %>
                <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content"></div>
                  </div>
                </div>
              </tbody>
            </table>
            <%= paginate @orders, theme: "twitter-bootstrap-4" %>
            <div class="col-lg-6">
              <div class="shoping__cart__btns">
                <%= link_to t(".continue_shopping"), products_path, class: "primary-btn cart-btn" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/orders_history/show.html.erb
<%= provide :title, t(".orders") %>
<section class="shoping-cart spad order-detail">
  <div class="order-detail-container">
    <div class="row">
      <div class="col-lg-12">
        <h1><%= t(".orders") + "#" + @order.id.to_s %></h1>
        <div class="shoping__cart__table">
          <table>
            <thead>
              <tr>
                <th class="shoping__product"><%= t ".product" %></th>
                <th><%= t ".quantity" %></th>
                <th><%= t ".total" %></th>
              </tr>
            </thead>
            <tbody>
              <%= render partial: "product_item",
                collection: @product_items, as: :order_detail %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3">
        <div class="shoping__cart__btns">
          <%= link_to t(".continue_shopping"), products_path %>
        </div>
      </div>
      <div class="col-lg-3">
        <div class="shoping__cart__btns">
          <%= link_to t(".history_orders"), orders_history_index_path %>
        </div>
      </div>
      <% if @order.present? %>
        <div class="col-lg-6">
          <div class="shoping__checkout">
            <h5><%= t ".total_checkout" %></h5>
            <ul>
              <li><%= t ".total" %>
                <span><%= number_to_currency @order.total_amount %></span>
              </li>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>