config/routes.rb
Rails.application.routes.draw do
  mount API::Base, at: "/"
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  scope "(:locale)", locale: /en|vi/ do
    require "sidekiq/web"
    mount Sidekiq::Web => "/sidekiq"
    root "products#index"
    devise_for :users, skip: :omniauth_callbacks
    resources :products
    resources :carts
    resources :orders
    resources :orders_history, only: %i(index show)
    namespace :admins do
      root "products#index"
      resources :products
      resources :users
      resources :orders
    end
  end
end

app/views/layouts/admins/layouts/_footer.html.erb
<footer class="py-4 bg-light mt-auto">
  <div class="container-fluid">
    <div class="d-flex align-items-center justify-content-between small">
      <div>
        <%= link_to t(".privacy"), "#" %>
        &middot;
        <%= link_to t(".terms"), "#" %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/admins/layouts/_navbar.html.erb
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
  <%= link_to t("brand"), "#", class: "navbar-brand" %>
  <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
  <!-- Navbar Search-->
  <div class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0 invisible">
  </div>
  <!-- Navbar-->
  <ul class="navbar-nav mr-auto mr-md-0">
    <li class="nav-item dropdown">
      <%= link_to "#", class: "nav-link dropdown-toggle", id: "userDropdown",  "data-role" => "button", data: { toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
        <i class="fas fa-user fa-fw"></i>
      <% end %>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
        <%= link_to t(".settings"), "#", class: "dropdown-item" %>
        <div class="dropdown-divider"></div>
        <%= link_to t(".logout"), destroy_user_session_path, class: "dropdown-item", method: :delete %>
      </div>
    </li>
  </ul>
</nav>

app/views/layouts/admins/layouts/_sidenav.html.erb
<div id="layoutSidenav_nav">
  <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
    <div class="sb-sidenav-menu">
      <div class="nav">
        <%= link_to "#", class: "nav-link collapsed", id: "userDropdown", "data-role": "button", data: {toggle: "collapse", target: "#collapseProducts"}, aria: {expanded: true, controls: "collapseLayouts"} do %>
          <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
          <%= t ".products" %>
          <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        <% end %>
        <div class="collapse" id="collapseProducts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
          <nav class="sb-sidenav-menu-nested nav">
            <%= link_to t(".list_products"), admins_products_path, class: "nav-link" %>
          </nav>
          <nav class="sb-sidenav-menu-nested nav">
            <%= link_to t(".create_product"), new_admins_product_path, class: "nav-link" %>
          </nav>
        </div>
      </div>
      <div class="nav">
        <%= link_to "#", class: "nav-link collapsed", id: "userDropdown", "data-role" => "button", data: {toggle: "collapse", target: "#collapseOrders"}, aria: {expanded: true, controls: "collapseLayouts"} do %>
          <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
          <%= t ".orders" %>
          <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        <% end %>
        <div class="collapse" id="collapseOrders" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
          <nav class="sb-sidenav-menu-nested nav">
            <%= link_to t(".list_orders"), admins_orders_path, class: "nav-link" %>
          </nav>
          <nav class="sb-sidenav-menu-nested nav">
            <%= link_to t(".create_order"), "#", class: "nav-link" %>
          </nav>
        </div>
      </div>
      <div class="nav">
        <%= link_to "#", class: "nav-link collapsed", id: "userDropdown", "data-role" => "button", data: {toggle: "collapse", target: "#collapseUsers"}, aria: {expanded: true, controls: "collapseLayouts"} do %>
          <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
          <%= t ".users" %>
          <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        <% end %>
        <div class="collapse" id="collapseUsers" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
          <nav class="sb-sidenav-menu-nested nav">
            <%= link_to t(".list_users"), admins_users_path, class: "nav-link" %>
          </nav>
          <nav class="sb-sidenav-menu-nested nav">
            <%= link_to t(".create_user"), new_admins_user_path, class: "nav-link" %>
          </nav>
        </div>
      </div>
    </div>
    <div class="sb-sidenav-footer">

    <% if user_signed_in? %>
      <div class="small"><%= t ".login_as" %></div>
        <%= current_user.name %>
      </div>
    <% end %>
  </nav>
</div>