config/routes.rb
Rails.application.routes.draw do
  mount API::Base, at: "/"
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  scope "(:locale)", locale: /en|vi/ do
    require "sidekiq/web"
    mount Sidekiq::Web => "/sidekiq"
    root "products#index"
    devise_for :users, skip: :omniauth_callbacks
    resources :products
    resources :carts
    resources :orders
    resources :orders_history, only: %i(index show)
    namespace :admins do
      root "products#index"
      resources :products
      resources :users
      resources :orders
    end
  end
end

app/views/layouts/_header.html.erb
<!-- Humberger Begin -->
<div class="humberger__menu__overlay"></div>
<div class="humberger__menu__wrapper">
  <div class="humberger__menu__logo">
    <%= link_to root_path do %>
      <%= image_tag("https://res.cloudinary.com/tdh/image/upload/v1595343877/images/language_uyra3n.png") %>
    <% end %>
  </div>
  <div class="humberger__menu__cart">
    <ul>
      <li>
        <%= link_to "#" do %>
          <i class="fa fa-heart"></i>
          <span>1</span>
        <% end %>
      </li>
      <li>
        <%= link_to carts_path do %>
          <i class="fa fa-shopping-bag"></i>
          <span class="length-cart">
            <%= session[:cart].length if session[:cart]%>
          </span>
        <% end %>
      </li>
    </ul>
  </div>
  <div class="humberger__menu__widget">
    <div class="header__top__right__language">
      <%= image_tag(Settings.language_image, class: "") %>
      <div><%= I18n.locale %></div>
      <span class="arrow_carrot-down"></span>
      <ul>
        <li><%= link_to t("layouts.header.vietnamese"), locale: "vi" %></li>
        <li><%= link_to t("layouts.header.english"), locale: "en" %></li>
      </ul>
    </div>
    <div class="header__top__right__auth">
      <% if user_signed_in? %>
        <li class="dropdown li-none">
          <%= link_to "#", class: "dropdown-toggle", "data-toggle": "dropdown" do %>
            <%= current_user.name %>
            <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <li class="divider"></li>
            <%= link_to t("layouts._header.logout"), destroy_user_session_path , method: :delete %>
            <li class="divider"></li>
            <%= link_to t("layouts._header.edit_account"), "#" %>
            <% if current_user.role_admin?  %>
              <li class="divider"></li>
              <%= link_to t("layouts._header.enter_admin"), admins_root_path %>
            <% end %>
          </ul>
        </li>
      <% else %>
        <%= link_to new_user_session_path do %>
          <i class="fa fa-user"></i>
          <%= t "layouts._header.login" %>
        <% end %>
      <% end %>
    </div>
  </div>
  <nav class="humberger__menu__nav mobile-menu">
    <ul>
      <li class="active">
        <%= link_to t("layouts._header.home"), "#" %>
      </li>
      <li>
        <%= link_to t("layouts._header.products"), "#" %>
      </li>
      <li>
        <%= link_to t("layouts._header.help"), "#" %>
      </li>
    </ul>
  </nav>
  <div id="mobile-menu-wrap"></div>
</div>
<!-- Humberger End -->

<!-- Header Section Begin -->
<header class="header">
  <div class="header__top">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-6">
        </div>
        <div class="col-lg-6 col-md-6">
          <div class="header__top__right">
            <div class="header__top__right__language">
              <%= image_tag("https://res.cloudinary.com/tdh/image/upload/v1595343877/images/language_uyra3n.png") %>
              <div><%= I18n.locale %></div>
              <span class="arrow_carrot-down"></span>
              <ul>
                <li><%= link_to t("layouts.header.vietnamese"), locale: "vi" %></li>
                <li><%= link_to t("layouts.header.english"), locale: "en" %></li>
              </ul>
            </div>
            <div class="header__top__right__auth">
              <% if user_signed_in? %>
                <li class="dropdown li-none">
                  <%= link_to "#", class: "dropdown-toggle", "data-toggle": "dropdown" do %>
                    <%= current_user.name %>
                    <b class="caret"></b>
                  <% end %>
                  <ul class="dropdown-menu">
                    <%= link_to t("layouts.header.edit_account"), edit_user_registration_path %>
                     <li class="divider"></li>
                    <%= link_to t("layouts.header.order_history"), orders_history_index_path %>
                    <li class="divider"></li>
                    <%= link_to t("layouts.header.logout"), destroy_user_session_path, method: :delete %>
                    <% if current_user.role_admin?  %>
                      <li class="divider"></li>
                      <%= link_to t("layouts.header.enter_admin"), admins_root_path %>
                    <% end %>
                  </ul>
                </li>
              <% else %>
                <%= link_to new_user_session_path do %>
                  <i class="fa fa-user"></i>
                  <%= t "layouts.header.login" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-3">
        <div class="header__logo">
          <%= link_to root_path do %>
            <%= image_tag("https://dt2sdf0db8zob.cloudfront.net/wp-content/uploads/2019/08/image13.png") %>
          <% end %>
        </div>
      </div>
      <div class="col-lg-6">
        <nav class="header__menu">
          <ul>
            <li>
              <%= link_to t("layouts._header.home"), root_path %>
            </li>
            <li>
              <%= link_to t("layouts._header.shop"), root_path %>
            </li>
          </ul>
        </nav>
      </div>
      <div class="col-lg-3">
        <div class="header__cart">
          <ul>
            <li>
              <%= link_to carts_path do %>
                <i class="fa fa-shopping-bag"></i>
                <span class="length-cart">
                  <%= session[:cart].length if session[:cart] %>
                </span>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="lol-lg-3">
      <div class="toast">

      </div>
    </div>
    <div class="humberger__open">
      <i class="fa fa-bars"></i>
    </div>
  </div>
</header>
<!-- Header Section End -->

app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "admins/admins", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "admins/font-awesome-all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "admins", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "toastr", "data-turbolinks-track": "reload" %>
  </head>
  <body class="sb-nav-fixed">
    <%= render "shared/toastr" %>
    <%= render "layouts/admins/layouts/navbar" %>
    <div id="layoutSidenav">
      <%= render "layouts/admins/layouts/sidenav" %>
      <div id="layoutSidenav_content">
        <%= yield %>
        <%= render "layouts/admins/layouts/footer" %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t "layouts.application.title" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "toastr", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "shared/toastr" %>
    <%= render "layouts/header" %>
    <div class="toast custom-toast" role="alert" aria-live="assertive" aria-atomic="true" data-delay="2000">
      <div class="toast-body">
        <%= t ".updated_cart" %>
      </div>
    </div>

    <%= yield %>
  </body>
  <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
</html>